In [24]:
#imports
import numpy as np
import pandas as pd
import math

## Zadanie 1

In [6]:
df_1 = pd.read_csv('csv/Zadanie_1.csv', delimiter=";")
df_1.head()

arr_1 = df_1.to_numpy()

print(f"Number of elements is {arr_1.size}")
print(f"Shape of the matrix is {arr_1.shape}")


print(f"""
Mean for matrix is     : {np.nanmean(arr_1)}
Median for matrix is   : {np.nanmedian(arr_1)}
Variance for matrix is : {np.nanvar(arr_1)}
""")

print(np.isnan(arr_1).any())

arr_1 = arr_1[~np.isnan(arr_1).any(axis=1)]

print(f"""
Mean for matrix is     : {np.nanmean(arr_1)}
Median for matrix is   : {np.nanmedian(arr_1)}
Variance for matrix is : {np.nanvar(arr_1)}
""")


Number of elements is 960
Shape of the matrix is (60, 16)

Mean for matrix is     : 338.2209319148936
Median for matrix is   : 33.4
Variance for matrix is : 1036473.5935947594

True

Mean for matrix is     : 332.2025610465116
Median for matrix is   : 34.0
Variance for matrix is : 1042134.7488820893



## Zadanie 2

In [15]:
arr_2 = pd.read_csv('csv/Zadanie_2.csv', delimiter=";", header=None).to_numpy()
eigvs = np.linalg.eig(arr_2)
print(f"""
Eigenvalues of matrix: {eigvs[0]}
Eigenvectors of matrix: {eigvs[1]}
""")

print('=====================================================')



Eigenvalues of matrix: [104.34960192 +0.j         -23.35660516+18.84992811j
 -23.35660516-18.84992811j  15.92989017 +0.j
  -4.99456452 +0.j           0.35205717 +5.80125175j
   0.35205717 -5.80125175j  -1.03383491 +0.j
   3.87900166 +1.42651533j   3.87900166 -1.42651533j]
Eigenvectors of matrix: [[-0.29000475+0.j         -0.07545445+0.07743149j -0.07545445-0.07743149j
  -0.03544485+0.j          0.42681634+0.j         -0.22172831-0.29869259j
  -0.22172831+0.29869259j  0.41343726+0.j         -0.28670255+0.21891569j
  -0.28670255-0.21891569j]
 [-0.24163153+0.j          0.41229621+0.09197324j  0.41229621-0.09197324j
   0.45873475+0.j         -0.27056206+0.j         -0.01331344+0.1422557j
  -0.01331344-0.1422557j  -0.31591047+0.j          0.41954481-0.10561864j
   0.41954481+0.10561864j]
 [-0.41060573+0.j          0.37509638-0.00960818j  0.37509638+0.00960818j
   0.64067986+0.j         -0.37967609+0.j         -0.60525232+0.j
  -0.60525232-0.j          0.6457768 +0.j          0.63631555+0.j

In [12]:
print(f'Transposed matrix is {np.linalg.inv(arr_2)}')

Transposed matrix is [[ 0.47461371  0.13269253 -0.24726695 -0.82965177  0.28250384 -0.17012825
   0.58274426  0.83686705  0.4146721  -1.56942847]
 [-0.38032531 -0.11226789  0.23216372  0.58853747 -0.2508954   0.10174485
  -0.40729564 -0.58325689 -0.2335154   1.11832726]
 [ 0.13559662  0.58950334 -0.24709855 -0.58789838 -0.30170699 -0.12721938
   0.23740295  1.01003036 -0.02151387 -0.64590149]
 [ 0.01425207  0.14570726 -0.04557569 -0.12721972 -0.08945184 -0.03756624
   0.03910376  0.23606066 -0.01436771 -0.11345749]
 [-0.09473246  0.01725249  0.19145597  0.32960274 -0.28626296  0.08348529
  -0.37577603 -0.27295934 -0.25855803  0.74691827]
 [ 0.16387032  0.10075684 -0.15404907 -0.29794662  0.16916877 -0.02827782
   0.20469921  0.28036265  0.15086178 -0.5882585 ]
 [ 0.04288003  0.02246462 -0.0366803  -0.09024915  0.04322146 -0.01047861
   0.06167348  0.07009721  0.0367806  -0.14185925]
 [-0.26858433 -0.21167346  0.25168367  0.55607234 -0.16804333  0.01066975
  -0.22435849 -0.52957038 -0.1

## Zadanie 3

In [26]:
#Read data
arr_3_a = pd.read_csv('csv/Zadanie_3_macierz_A.csv', header=None).to_numpy()
arr_3_b = pd.read_csv('csv/Zadanie_3_macierz_B.csv', header=None).to_numpy()

In [29]:
#Functions

def sum(arr):
    s = 0
    for i in range(len(arr)):
        s = s + arr[i]
    return s

def norm(arr):
    n = 0
    for i in range(len(arr)):
        n = n + (arr[i] ** 2)
    
    return math.sqrt(n)

def cos_sim(a,b):
    arr_out = []
    for i in range(len(a)):
        a_i = a[i]
        a_i_vec = sum(a_i)
        a_i_norm = norm(a_i)
        layer = []
        for j in range(len(b)):
            b_j = b[j]
            b_j_vec = sum(b_j)
            b_j_norm = norm(b_j)
            res = (a_i_vec * b_j_vec) / (a_i_norm * b_j_norm)
            layer.append(res)

        arr_out.append(layer)

    return np.array(arr_out)


    

In [30]:
out = cos_sim(arr_3_a, arr_3_b)
print(out.shape)
print(out)

(3, 5)
[[2.47972168 2.89569106 2.49517181 2.64072614 2.27776981]
 [1.77122977 2.06835076 1.78226558 1.88623296 1.62697843]
 [2.49400889 2.91237493 2.50954803 2.65594099 2.29089344]]


## Zadanie 4

In [38]:
#TODO
#df = pd.read_csv('csv/Zadanie_4.csv', delimiter=';')
#df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

#df.head()
#df["DateTime"] = pd.to_datetime(df["DateTime"])
#df = df.groupby(["DoctorID",df["DateTime"].count()])
#df.head()

KeyError: 199